# Generated by Django 3.0.7 on 2020-06-29 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200629_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='profile_picture',
            new_name='picture',
        ),
    ]
